// <auto-generated />
using System;
using ControlEquiposElectronicos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlEquiposElectronicos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507194158_AjusteRolUnicoUsuarios")]
    partial class AjusteRolUnicoUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Auditoria.HistorialEstadoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoAnteriorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialEstadosEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Auditoria.HistorialOperacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaOperacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("TablaAfectada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialOperaciones");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.CategoriaEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BTU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimoServicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoAmbiental")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("DetallesAmbiental");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleComputadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlmacenamientoCapacidadGB")
                        .HasColumnType("int");

                    b.Property<string>("AlmacenamientoTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroEquipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procesador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RamGB")
                        .HasColumnType("int");

                    b.Property<string>("SerialRam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SistemaOperativo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("DetallesComputadora");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleImpresora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContadorImpresiones")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimoCambioCartucho")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModeloCartucho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCartucho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoImpresora")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("DetallesImpresora");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleRed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadPuertos")
                        .HasColumnType("int");

                    b.Property<string>("DireccionIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("MacAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesRed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PuertosDanados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.HasIndex("EquipoProveedorId");

                    b.ToTable("DetallesRed");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleUPS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapacidadVA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoBateria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCambioBateria")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("DetallesUPS");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaEquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoEquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInstalacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaEquipoId");

                    b.HasIndex("EstadoEquipoId");

                    b.HasIndex("TipoEquipoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.EstadoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.SwitchPuerto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipoConectadoId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaDanado")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaOcupado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroPuerto")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SwitchEquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionDestinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoConectadoId");

                    b.HasIndex("SwitchEquipoId");

                    b.HasIndex("UbicacionDestinoId");

                    b.ToTable("SwitchPuertos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.TipoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaEquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaEquipoId");

                    b.ToTable("TiposEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUbicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Mantenimientos.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CostoEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoMantenimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReporteFallaId")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMantenimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("ReporteFallaId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("TipoMantenimientoId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Mantenimientos.MantenimientoRepuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("MantenimientoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreRepuesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerieAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerieNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MantenimientoId");

                    b.ToTable("MantenimientoRepuestos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Mantenimientos.TipoMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposMantenimiento");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Reportes.EstadoReporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosReporte");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Reportes.ReclasificacionEquipo", b =>
                {
                    b.Property<int>("ReclasificacionEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReclasificacionEquipoId"));

                    b.Property<string>("CodigoAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoAnteriorId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoNuevoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReclasificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoReclasificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UbicacionAnteriorId")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionNuevaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ReclasificacionEquipoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("UbicacionAnteriorId");

                    b.HasIndex("UbicacionNuevaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ReclasificacionesEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Reportes.ReporteFalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoReporteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacionesCierre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioReportaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("EstadoReporteId");

                    b.HasIndex("UsuarioReportaId");

                    b.ToTable("ReportesFalla");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Modulo", "Accion")
                        .IsUnique();

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RolId");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<bool>("Permitido")
                        .HasColumnType("bit");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId", "PermisoId")
                        .IsUnique();

                    b.ToTable("RolPermisos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Auditoria.HistorialEstadoEquipo", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.EstadoEquipo", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.EstadoEquipo", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany("HistorialEstadosEquipo")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Auditoria.HistorialOperacion", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany("HistorialOperaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleAmbiental", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithOne("DetalleAmbiental")
                        .HasForeignKey("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleAmbiental", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleComputadora", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithOne("DetalleComputadora")
                        .HasForeignKey("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleComputadora", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleImpresora", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithOne("DetalleImpresora")
                        .HasForeignKey("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleImpresora", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleRed", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithOne("DetalleRed")
                        .HasForeignKey("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleRed", "EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "EquipoProveedor")
                        .WithMany()
                        .HasForeignKey("EquipoProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipo");

                    b.Navigation("EquipoProveedor");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleUPS", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithOne("DetalleUPS")
                        .HasForeignKey("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleUPS", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.CategoriaEquipo", "CategoriaEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("CategoriaEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.EstadoEquipo", "EstadoEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("EstadoEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.TipoEquipo", "TipoEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("TipoEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Ubicacion", "Ubicacion")
                        .WithMany("Equipos")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaEquipo");

                    b.Navigation("EstadoEquipo");

                    b.Navigation("TipoEquipo");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.SwitchPuerto", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "EquipoConectado")
                        .WithMany()
                        .HasForeignKey("EquipoConectadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "SwitchEquipo")
                        .WithMany()
                        .HasForeignKey("SwitchEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Ubicacion", "UbicacionDestino")
                        .WithMany()
                        .HasForeignKey("UbicacionDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EquipoConectado");

                    b.Navigation("SwitchEquipo");

                    b.Navigation("UbicacionDestino");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.TipoEquipo", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.CategoriaEquipo", "CategoriaEquipo")
                        .WithMany("TiposEquipo")
                        .HasForeignKey("CategoriaEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Mantenimientos.Mantenimiento", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Reportes.ReporteFalla", "ReporteFalla")
                        .WithMany()
                        .HasForeignKey("ReporteFallaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Usuario", "Tecnico")
                        .WithMany("MantenimientosRealizados")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Mantenimientos.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("TipoMantenimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("ReporteFalla");

                    b.Navigation("Tecnico");

                    b.Navigation("TipoMantenimiento");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Mantenimientos.MantenimientoRepuesto", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Mantenimientos.Mantenimiento", "Mantenimiento")
                        .WithMany("Repuestos")
                        .HasForeignKey("MantenimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mantenimiento");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Reportes.ReclasificacionEquipo", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.EstadoEquipo", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.EstadoEquipo", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Ubicacion", "UbicacionAnterior")
                        .WithMany()
                        .HasForeignKey("UbicacionAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Ubicacion", "UbicacionNueva")
                        .WithMany()
                        .HasForeignKey("UbicacionNuevaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany("ReclasificacionesRealizadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("UbicacionAnterior");

                    b.Navigation("UbicacionNueva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Reportes.ReporteFalla", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Reportes.EstadoReporte", "EstadoReporte")
                        .WithMany("ReportesFalla")
                        .HasForeignKey("EstadoReporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Usuario", "UsuarioReporta")
                        .WithMany("ReportesRealizados")
                        .HasForeignKey("UsuarioReportaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("EstadoReporte");

                    b.Navigation("UsuarioReporta");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.RolPermiso", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Usuario", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.CategoriaEquipo", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("TiposEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", b =>
                {
                    b.Navigation("DetalleAmbiental");

                    b.Navigation("DetalleComputadora");

                    b.Navigation("DetalleImpresora");

                    b.Navigation("DetalleRed");

                    b.Navigation("DetalleUPS");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.EstadoEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.TipoEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.Ubicacion", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Mantenimientos.Mantenimiento", b =>
                {
                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Mantenimientos.TipoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Reportes.EstadoReporte", b =>
                {
                    b.Navigation("ReportesFalla");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Usuario", b =>
                {
                    b.Navigation("HistorialEstadosEquipo");

                    b.Navigation("HistorialOperaciones");

                    b.Navigation("MantenimientosRealizados");

                    b.Navigation("ReclasificacionesRealizadas");

                    b.Navigation("ReportesRealizados");
                });
#pragma warning restore 612, 618
        }
    }
}
