// <auto-generated />
using System;
using ControlEquiposElectronicos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlEquiposElectronicos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507044906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.CategoriaEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BTU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimoServicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoAmbiental")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("DetallesAmbiental");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleComputadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlmacenamientoCapacidadGB")
                        .HasColumnType("int");

                    b.Property<string>("AlmacenamientoTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroEquipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procesador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RamGB")
                        .HasColumnType("int");

                    b.Property<string>("SerialRam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SistemaOperativo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("DetallesComputadora");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleImpresora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContadorImpresiones")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimoCambioCartucho")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModeloCartucho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCartucho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoImpresora")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("DetallesImpresora");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleRed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadPuertos")
                        .HasColumnType("int");

                    b.Property<string>("DireccionIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("MacAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesRed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PuertosDanados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.HasIndex("EquipoProveedorId");

                    b.ToTable("DetallesRed");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleUPS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapacidadVA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoBateria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCambioBateria")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId")
                        .IsUnique();

                    b.ToTable("DetallesUPS");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaEquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoEquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInstalacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaEquipoId");

                    b.HasIndex("EstadoEquipoId");

                    b.HasIndex("TipoEquipoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.EstadoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.SwitchPuerto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipoConectadoId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaDanado")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaOcupado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroPuerto")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SwitchEquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionDestinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoConectadoId");

                    b.HasIndex("SwitchEquipoId");

                    b.HasIndex("UbicacionDestinoId");

                    b.ToTable("SwitchPuertos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.TipoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaEquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaEquipoId");

                    b.ToTable("TiposEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUbicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<bool>("Permitido")
                        .HasColumnType("bit");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId");

                    b.ToTable("RolPermisos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleAmbiental", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithOne("DetalleAmbiental")
                        .HasForeignKey("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleAmbiental", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleComputadora", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithOne("DetalleComputadora")
                        .HasForeignKey("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleComputadora", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleImpresora", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithOne("DetalleImpresora")
                        .HasForeignKey("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleImpresora", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleRed", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithOne("DetalleRed")
                        .HasForeignKey("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleRed", "EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "EquipoProveedor")
                        .WithMany()
                        .HasForeignKey("EquipoProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipo");

                    b.Navigation("EquipoProveedor");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleUPS", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "Equipo")
                        .WithOne("DetalleUPS")
                        .HasForeignKey("ControlEquiposElectronicos.Api.Entities.Inventario.DetalleUPS", "EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.CategoriaEquipo", "CategoriaEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("CategoriaEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.EstadoEquipo", "EstadoEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("EstadoEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.TipoEquipo", "TipoEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("TipoEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Ubicacion", "Ubicacion")
                        .WithMany("Equipos")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaEquipo");

                    b.Navigation("EstadoEquipo");

                    b.Navigation("TipoEquipo");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.SwitchPuerto", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "EquipoConectado")
                        .WithMany()
                        .HasForeignKey("EquipoConectadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", "SwitchEquipo")
                        .WithMany()
                        .HasForeignKey("SwitchEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.Ubicacion", "UbicacionDestino")
                        .WithMany()
                        .HasForeignKey("UbicacionDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EquipoConectado");

                    b.Navigation("SwitchEquipo");

                    b.Navigation("UbicacionDestino");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.TipoEquipo", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Inventario.CategoriaEquipo", "CategoriaEquipo")
                        .WithMany("TiposEquipo")
                        .HasForeignKey("CategoriaEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.RolPermiso", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Usuario", b =>
                {
                    b.HasOne("ControlEquiposElectronicos.Api.Entities.Seguridad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.CategoriaEquipo", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("TiposEquipo");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.Equipo", b =>
                {
                    b.Navigation("DetalleAmbiental");

                    b.Navigation("DetalleComputadora");

                    b.Navigation("DetalleImpresora");

                    b.Navigation("DetalleRed");

                    b.Navigation("DetalleUPS");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.EstadoEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.TipoEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Inventario.Ubicacion", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("ControlEquiposElectronicos.Api.Entities.Seguridad.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
